# Generated by Django 3.0.1 on 2019-12-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20191228_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='categroy',
            new_name='category',
        ),
    ]
